import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import I18nProvider from "@/lib/i18nProvider";
import ReduxProvider from "@/provider/ReduxProvider";
import { Toaster } from "sonner";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "My Gasked",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} `}>
        <ReduxProvider>
          <I18nProvider>
            <Toaster position="top-right" richColors />
            {children}

          </I18nProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
